ModelType: 'MAF'
Transform: 'Affine'
optimizer: 'Adam'
num_inputs: 5
num_cond_inputs: 1
num_blocks: 15
num_hidden: 128
activation_function: 'relu'
pre_exp_tanh: false
batch_norm: true
batch_norm_momentum: 1

optimizer:
  name: Adam
  lr: 0.0001
  weight_decay: 0.000001
